// obtained from https://developers.giphy.com/docs/optional-settings/#language-support
export enum LanguageCode {
  English = "en",
  Spanish = "es",
  Portuguese = "pt",
  Indonesian = "id",
  French = "fr",
  Arabic = "ar",
  Turkish = "tr",
  Thai = "th",
  Vietnamese = "vi",
  German = "de",
  Italian = "it",
  Japanese = "ja",
  ChineseSimplified ="zh-CN",
  ChineseTraditional ="zh-TW",
  Russian = "ru",
  Korean = "ko",
  Polish = "pl",
  Dutch = "nl",
  Romanian = "ro",
  Hungarian = "hu",
  Swedish = "sv",
  Czech = "cs",
  Hindi = "hi",
  Bengali = "bn",
  Danish = "da",
  Farsi = "fa",
  Filipino = "tl",
  Finnish = "fi",
  Hebrew = "he",
  Malay = "ms",
  Norwegian = "no",
  Ukrainian = "uk",
};
